// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQty_fPwX6XtTS5VdsE2DtrcBHb_FjmFA',
    appId: '1:209994691854:web:56ceb5ffed45258412935f',
    messagingSenderId: '209994691854',
    projectId: 'codebxo',
    authDomain: 'codebxo.firebaseapp.com',
    storageBucket: 'codebxo.firebasestorage.app',
    measurementId: 'G-QJJL9HCNDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2msV_dDECkkl5oc-E6FwyJAiu-Zi3dQ',
    appId: '1:209994691854:android:5143e2c241bdd17a12935f',
    messagingSenderId: '209994691854',
    projectId: 'codebxo',
    storageBucket: 'codebxo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwmzoLX4k0bOhdE02_KKCk7zm-arDItrI',
    appId: '1:209994691854:ios:1228dd20f5c1282912935f',
    messagingSenderId: '209994691854',
    projectId: 'codebxo',
    storageBucket: 'codebxo.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwmzoLX4k0bOhdE02_KKCk7zm-arDItrI',
    appId: '1:209994691854:ios:1228dd20f5c1282912935f',
    messagingSenderId: '209994691854',
    projectId: 'codebxo',
    storageBucket: 'codebxo.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQty_fPwX6XtTS5VdsE2DtrcBHb_FjmFA',
    appId: '1:209994691854:web:70a7642469c4cd3712935f',
    messagingSenderId: '209994691854',
    projectId: 'codebxo',
    authDomain: 'codebxo.firebaseapp.com',
    storageBucket: 'codebxo.firebasestorage.app',
    measurementId: 'G-KY59JYX86B',
  );
}
